Include addon status models
openshift-online/ocm-api-model pull request #649
Opened 2022-11-29 13:44 UTC by ashishmax31

2022-11-30 15:07 UTC, tzvatot requested changes

2022-11-30 15:07 UTC, tzvatot commented on model/addons_mgmt/v1/addon_clusters_resource.model
> +        variable ID
Looks like indentation issue

2022-12-06 12:15 UTC, ciaranRoche commented on model/addons_mgmt/v1/addon_status_type.model
> +    // Identifier for co-relating current AddonCR revision and reported status.
We are missing the addon_id from here 

https://gitlab.cee.redhat.com/ocm/ocm-addons-service/-/blob/main/openapi/ocm-addons-service.yaml#L769

2022-12-06 12:20 UTC, ciaranRoche commented on model/addons_mgmt/v1/addon_status_type.model
> +    // Identifier for co-relating current AddonCR revision and reported status.
looks like that is all that is missing, i am able to create, get, list and delete using the SDK when I added the addon_id

2022-12-06 12:23 UTC, ciaranRoche commented on model/addons_mgmt/v1/addon_status_type.model
> +    AddOnStatusConditions []AddonStatusCondition
Should just be `StatusConditions`

2022-12-07 14:25 UTC, ciaranRoche commented
LGTM

@tzvatot PTAL if you are happy with your requested changes, can you merge this please :pray:

2022-12-08 14:26 UTC, tzvatot commented
LGTM

2022-12-08 14:26 UTC, merged

2022-12-08 15:11 UTC, ciaranRoche commented
JIRA - https://issues.redhat.com/browse/SDA-7381

2022-12-08 15:12 UTC, ciaranRoche commented
JIRA - https://issues.redhat.com/browse/SDA-7380