Add DeletedSubscription resource model
openshift-online/ocm-api-model pull request #651
Opened 2022-12-07 18:45 UTC by tylercreller

2022-12-08 16:07 UTC, rawsyntax commented
@tbrisker @tzvatot Please take a look

2022-12-08 16:13 UTC, tzvatot requested changes

2022-12-08 16:15 UTC, tylercreller commented on CHANGES.md
> +- Updated `AddOnStatusType` for `StatusConditions` and `AddonId`
Looks like there may have been additional changes on that PR, I can get those added in here as well

2022-12-11 11:22 UTC, Lir10 commented
lgtm

2022-12-12 15:10 UTC, tzvatot commented
I'm missing a GET for DeletedSubscription. Every object in the list should have an HREF that is a target for a GET.

2022-12-12 15:22 UTC, tylercreller commented
> I'm missing a GET for DeletedSubscription. Every object in the list should have an HREF that is a target for a GET.

DeletedSubscriptions from AMS does not support fetching single resources by id, so we only need List at the moment. Let me know if I am misunderstanding the ask.

2022-12-12 15:30 UTC, tzvatot commented
> 

I

> > I'm missing a GET for DeletedSubscription. Every object in the list should have an HREF that is a target for a GET.
> 
> DeletedSubscriptions from AMS does not support fetching single resources by id, so we only need List at the moment. Let me know if I am misunderstanding the ask.

I suggest the AMS backend will support fetching a single resource by ID.

2022-12-12 15:51 UTC, tylercreller commented
Created SDB-3364 as a future enhancement

2022-12-12 15:55 UTC, rawsyntax commented
+1 to addressing it in a future PR

2022-12-13 14:35 UTC, cristianoveiga commented
LGTM

2022-12-13 14:38 UTC, merged