OCM-6294 | add get /load_balancer_quota_values
openshift-online/ocm-api-model pull request #922
Opened 2024-04-01 13:34 UTC by ahitacat

This PR adds a new endpoint to get load_balancer_quota_values.

It uses the GET method. Using the list method was discarded because this endpoint returns a list of integers, at this moment the meta-model doesn't allow it and it cannot build the SDK.

Issue: https://issues.redhat.com/browse/OCM-6294

2024-04-02 07:29 UTC, tzvatot requested changes

2024-04-02 07:29 UTC, tzvatot commented on model/clusters_mgmt/v1/load_balancer_quota_values_resource.model
> +        out Body LoadBalancerQuotaValues
Something is off with the indentation.

2024-04-02 07:29 UTC, tzvatot commented on model/clusters_mgmt/v1/load_balancer_quota_values_type.model
> +Copyright (c) 2020 Red Hat, Inc.
2024

2024-04-02 07:29 UTC, tzvatot commented on model/clusters_mgmt/v1/load_balancer_quota_values_type.model
> +            // Retrieved list of values.
Perhaps change "values" to "items"

2024-04-02 08:08 UTC, ahitacat commented on model/clusters_mgmt/v1/load_balancer_quota_values_resource.model
> +        out Body LoadBalancerQuotaValues
Yeah, it's using spaces. Good catch!

2024-04-03 12:54 UTC, closed without merging

2024-04-03 12:54 UTC, ahitacat commented
I'm closing this one in favor of #921